### ISSUE TITLE
unable to download pretrained model

### ISSUE THREAD

**Issue by hungtooc** [EricDengbowen/DSLRDNet#1]
unable to download pretrained model

**Comment by EricDengbowen** [comment]
Please try to directly copy the link on your browser

http://cvl.cs.nott.ac.uk/resources/dslrd.pretrained.zip

**Comment by EricDengbowen** [comment]
> unable to download pretrained model

Please try to directly copy the link on your browser

http://cvl.cs.nott.ac.uk/resources/dslrd.pretrained.zip
